name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "30.0.3"
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: CommentGenerator-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: CommentGenerator-release
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: CommentGenerator v${{ github.run_number }}
        body: |
          🚀 Nouvelle version de CommentGenerator !
          
          ## 📱 Installation
          1. Téléchargez le fichier APK ci-dessous
          2. Activez les sources inconnues sur votre téléphone
          3. Installez l'APK
          4. Entrez votre clé API DeepSeek
          5. Profitez de la pastille flottante !
          
          ## ✨ Fonctionnalités
          - Pastille flottante déplaçable
          - Prise de photo automatique
          - Génération de commentaires via IA
          - Copie automatique dans le presse-papiers
          - Gestes de contrôle intuitifs
          
          ## 🔧 Changements
          - Build automatique via GitHub Actions
          - Optimisations de performance
          - Corrections de bugs
        draft: false
        prerelease: false
        files: |
          app/build/outputs/apk/release/app-release-unsigned.apk
        
    - name: Send to Telegram (Optional)
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🎉 CommentGenerator v${{ github.run_number }} compilé avec succès !
          
          📱 Téléchargement disponible :
          https://github.com/${{ github.repository }}/releases/latest
          
          ✅ Build : ${{ job.status }}
          🔗 Commit : ${{ github.sha }}
          👤 Auteur : ${{ github.actor }}
        document: app/build/outputs/apk/release/app-release-unsigned.apk
        
    - name: Upload to Google Drive (Optional)
      if: success()
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.DRIVE_CREDENTIALS }}
        filename: app/build/outputs/apk/release/app-release-unsigned.apk
        name: CommentGenerator-v${{ github.run_number }}.apk
        folderId: ${{ secrets.DRIVE_FOLDER_ID }}
        
    - name: Send Email Notification (Optional)
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: CommentGenerator Build ${{ job.status }}
        body: |
          🚀 Build CommentGenerator terminé !
          
          Status: ${{ job.status }}
          Version: v${{ github.run_number }}
          Commit: ${{ github.sha }}
          Auteur: ${{ github.actor }}
          
          Téléchargement: https://github.com/${{ github.repository }}/releases/latest
        to: ${{ secrets.EMAIL_TO }}
        from: GitHub Actions
        attachments: app/build/outputs/apk/release/app-release-unsigned.apk
